var footerStr = '<footer>'
+ '    <div class="container-fluid text-center text-md-left">'
+ '        <div class="row">'
+ '            <div class="col-md-4">'
+ '                <h4 class="text-uppercase">Footer Content</h4>'
+ '                <p>Here you can use rows and columns here to organize your footer content.</p>'
+ '            </div>'
+ '            <div class="col-md-4">'
+ '                <h4 class="text-uppercase">Other Historic Schuylerville Attractions</h4>'
+ '                <ul class="list-unstyled">'
+ '                    <li><a target="_blank" href="https://parks.ny.gov/historic-sites/33/details.aspx">The Schuyler House</a></li>'
+ '                    <li><a target="_blank" href="https://www.nps.gov/sara/planyourvisit/saratoga-monument.htm">The Saratoga National Battle Monument</a></li>'
+ '                    <li><a target="_blank" href="https://www.nps.gov/sara/index.htm">The Saratoga Battlefield and the National Cemetery</a></li>'
+ '                    <li><a target="_blank" href="https://www.hudsoncrossingpark.org/virtualtour/StarksKnob.html">Starks Knob - NY\'s only volcano!</a></li>'
+ '                </ul>'
+ '            </div>'
+ '            <div class="col-md-4">'
+ '                <h4 class="text-uppercase">Friends and Sponsors</h4>'
+ '                <ul class="list-unstyled">'
+ '                    <li><a target="_blank" href="https://www.facebook.com/RockYourFitnessLLC">Rock Your Fitness LLC</a></li>'
+ '                    <li><a target="_blank" href="https://www.facebook.com/espressohuis">Espressohuis</a></li>'
+ '                    <li><a target="_blank" href="https://www.facebook.com/Footes-Amish-Sheds-514061188632358/">Foote\'s Amish Sheds</a></li>'
+ '                    <li class="tinyFont">Byron\'s Market</li>'
+ '                    <li class="tinyFont">Saratoga Ag and Sales</li>'
+ '                    <li class="tinyFont">Curtis Lumber</li>'
+ '                    <li class="tinyFont">Saratoga Apple</li>'
+ '                    <li class="tinyFont">Proven Winners</li>'
+ '                    <li class="tinyFont">Volunteers of Schuylerville and Victory</li>'
+ '                    <li class="tinyFont">Adirondack Financial</li>'
+ '                    <li class="tinyFont">Schuylerville Chamber of Commerce and all Schuylerville Businesses</li>'
+ '                </ul>'
+ '            </div>'
+ '        </div>'
+ '    </div>'
+ '    <div class="footer-copyright py-3 text-center">'
+ '        <div class="container horizontalFlex">'
+ '            <div>Website Design & Maintenance: <a href="https://www.webdevforgood.com">WebDev For Good</a></div>'
+ '            <div>© 2018 Copyright Schuyler Farms</div>'
+ '        </div>'
+ '    </div>'
+ '</footer>';
$(footerStr).insertAfter("#footer");
