var headerStr = '<div class="stickyHeader">'
+ '    <div class="container-fluid leftRightFlex hideOnMobile" style="height:200px">'
+ '        <div class="fillFlex" style="position:relative">'
+ '            <div class="bottomPosition">'
+ '                <h1 class="logo">Schuyler Farms</h1>'
+ '                <div class="leftRightFlex">'
+ '                    <h3 class="smallLogo">1124 Route 29 Schuylerville, NY</h3>'
+ '                    <h3 class="smallLogo">(518) 695-5308</h3>'
+ '                </div>'
+ '            </div>'
+ '        </div>'
+ '        <div>'
+ '            <div id="cont_212abdf045480c547054224c1801db1a"><script type="text/javascript" async src="https://www.theweather.com/wid_loader/212abdf045480c547054224c1801db1a"></script></div>'
+ '        </div>'
+ '    </div>'
+ '</div>'

+ '<nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="197">'
+ '    <div class="container-fluid">'
+ '        <div class="navbar-header">'
+ '            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">'
+ '                <span class="icon-bar"></span>'
+ '                <span class="icon-bar"></span>'
+ '                <span class="icon-bar"></span>'
+ '            </button>'
+ '            <a class="navbar-brand" href="index.html">SCHUYLER FARMS</a>'
+ '        </div>'
+ '        <div class="collapse navbar-collapse" id="myNavbar">'
+ '            <ul class="nav navbar-nav fullHorizontalFlex">'
+ '                <li id="index"><a href="index.html">Home</a></li>'
+ '                <li id="cornMaze"><a href="cornMaze.html">Corn Maze</a></li>'
+ '                <li id="hauntedMaze"><a href="hauntedMaze.html">Haunted Maze</a></li>'
+ '                <li id="gardenCenter"><a href="gardenCenter.html">Garden Center</a></li>'
+ '                <li id="otherAttractions"><a href="otherAttractions.html">Other Attractions</a></li>'
+ '                <li id="about"><a href="about.html">About the Farm</a></li>'
+ '            </ul>'
+ '        </div>'
+ '    </div>'
+ '</nav>';
$(headerStr).insertAfter("#header");
$("#" + (location.pathname.split('/').slice(-1)[0]).replace(".html","")).addClass("active");
